@startuml


object Systeme
object "Jean-Paul : Bookmaker" as Bookmaker


/' ---------- Les différents évènements sportifs disponibles : ---------- '/

/' Foot '/

object "Ligue 1 : Evenement" as EvenementF {
    Sport : Foot
}
object "abstract ResultatFoot" as AResultatFoot {
    Gagnant : Rennes
}
object ResultatFootball {
    scoreA1 : 10
    scoreB1 : 0
    scoreA2 : 5
    scoreB2 : 1
    equipeA : Rennes
    equipeB : OM
}
Bookmaker "1" --o "*" EvenementF
AResultatFoot "1" --o "1" EvenementF
ResultatFootball --|> AResultatFoot

/' Baseball '/

object "Un match de Baseball : Evenement" as EvenementB {
    Sport : Baseball
}
object "abstract ResultatBaseball" as  AResultatBaseball {
    Gagnant : Corgi
}
object ResultatBaseball { 
    scoreA : 60
    scoreB : 10000
}
Bookmaker "1" --o "*" EvenementB
AResultatBaseball "1" --o "1" EvenementB
ResultatBaseball --|> AResultatBaseball



/' ------------------- Les parieurs et leurs paris : ------------------- '/

/' Popol '/

object "Popol : Parieur" as ParieurP {
    NombreDeJetons : 10000
}
Systeme "1" -- "1" ParieurP : "< Credite / Debite"


/' Il fait un paris simple sur le match de Foot '/

object "abstract Ticket" as ATicketPF {
    Montant : 150
}
object "TicketSimple de Popol, Foot" as TicketSimplePF {
    PariGagnant : OM
}
Systeme o-- ATicketPF
TicketSimplePF --|> ATicketPF

object PariSimplePF

TicketSimplePF -- PariSimplePF : "Pointe sur >"
PariSimplePF "1...*" --o "1" EvenementF
PariSimplePF -- AResultatFoot : "< Lecture"
ATicketPF -- PariSimplePF
ATicketPF -- ParieurP

/'PariSimplePF --|> APari'/
/'object "abstract Pari" as APari'/
/'APari "1...*" --o "1" EvenementF
APari -- AResultatFoot : "< Lecture"
ATicketPF -- APari'/



@enduml